name: 'Terraform'
description: This task to deploy Azure resources using terraform
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
  tf_directory:
    description: 'Path to the terraform directory'
    required: true
  tf_plan:
    description: 'Terraform Plan'
    default: 'false'
  tf_apply:
    description: 'Terraform Apply'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      env:
        ARM_CLIENT_ID: "8b5273fc-e753-41cb-a3e0-a2ec8ece9a79"
        ARM_TENANT_ID: "bc540cd6-65a2-493d-8ec5-ee06f9bbb60e"
        ARM_SUBSCRIPTION_ID: "4b09b3ee-592e-48fd-a985-cb26811b0967"
        ARM_USE_OIDC: true
        
        
      run: |
        cd ${{ inputs.tf_directory }}
        terraform init
      shell: bash

    - name: Terraform Plan
      env:
        ARM_CLIENT_ID: "8b5273fc-e753-41cb-a3e0-a2ec8ece9a79"
        ARM_TENANT_ID: "bc540cd6-65a2-493d-8ec5-ee06f9bbb60e"
        ARM_SUBSCRIPTION_ID: "4b09b3ee-592e-48fd-a985-cb26811b0967"
        ARM_USE_OIDC: true
        
      run: |
        cd ${{ inputs.tf_directory }}
        terraform plan
      shell: bash
      if: inputs.tf_plan == 'true'

    - name: Terraform Apply
      env:
        ARM_CLIENT_ID: "8b5273fc-e753-41cb-a3e0-a2ec8ece9a79"
        ARM_TENANT_ID: "bc540cd6-65a2-493d-8ec5-ee06f9bbb60e"
        ARM_SUBSCRIPTION_ID: "4b09b3ee-592e-48fd-a985-cb26811b0967"
        ARM_USE_OIDC: true
      run: |
        cd ${{ inputs.tf_directory }}
        terraform apply -auto-approve
      shell: bash
      if: inputs.tf_apply == 'true'
        
  
