name: 'Terraform'
description: This task to deploy Azure resources using terraform
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
  tf_directory:
    description: 'Path to the terraform directory'
    required: true
  tf_plan:
    description: 'Terraform Plan'
    default: 'false'
  tf_apply:
    description: 'Terraform Apply'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: |
        cd ${{ inputs.tf_directory }}
        terraform init
      shell: bash

    - name: Terraform Plan
      run: |
        cd ${{ inputs.tf_directory }}
        terraform plan
      shell: bash
      if: inputs.tf_plan == 'true'
    
        
  
