name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
  client_id:
    description: 'test'
    required: true
  subscription_id:
    description: 'test'
    required: true
  tenant_id:
    description: 'test'
    required: true

runs:
  using: "composite"
  steps:
    # - name: Run Pester Tests
    #   continue-on-error: true
    #   run: |
    #     Invoke-Pester -Path "./s/Terraform/Azure.Resources/Test" -OutputFile "./s/Terraform/Azure.Resources/Test_Report.xml" 
    #   shell: pwsh
    - name: Azure account list
      run: |
        az account list
        az group list
      shell: bash

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: "8b5273fc-e753-41cb-a3e0-a2ec8ece9a79"
        tenant-id: "bc540cd6-65a2-493d-8ec5-ee06f9bbb60e"
        subscription-id: "4b09b3ee-592e-48fd-a985-cb26811b0967"
        enable-AzPSSession: true
        
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Invoke-Pester -Path "./s/Terraform/Azure.Resources/Test" -OutputFile "./s/Terraform/Azure.Resources/Test_Report.xml" 
        azPSVersion: "latest"
    # - name: Convert XML to HTML
    #   run: |
    #     ./s/Terraform/Azure.Resources/Tools/ReportUnit.exe -OutputFile ./s/Terraform/Azure.Resources/Test_Report.xml ./s/Terraform/Azure.Resources/HTML_Reports/
    #   shell: bash

    # - name: Upload Artifacts
    #   if: ${{ failure() }}
    #   uses: action/upload-artifact@v3
    #   with:
    #     name: HTML_Report
    #     path: ./s/Terraform/Azure.Resources/Test_Report.xml
