name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
runs:
  using: "composite"
  steps:
    # - name: Run Pester Tests
    #   run: |
    #     Invoke-Pester -Path "./s/Terraform/Azure.Resources/Tests*" -OutputFile "./s/Terraform/Azure.Resources/Test_Report.xml"
    #   shell: pwsh
    - name: test module
      id: test_module
      uses: zyborg/pester-tests-report@v1
      with:
        include_paths: ./s/Terraform/Azure.Resources/Test
        report_name: module_tests
        report_title: My Module Tests
        