name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Pester Tests
      run: |
        Invoke-Pester -Path "./s/Terraform/Azure.Resources/Tests*"
      shell: pwsh