name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
    default: test
runs:
  using: "composite"
  steps:
    - name: Run Pester Tests
      continue-on-error: true
      run: |
        Invoke-Pester -Path "./s/Terraform/Azure.Resources/Test" -OutputFile "./s/Terraform/Azure.Resources/Test_Report.xml" 
      shell: pwsh
    # - name: Convert XML to HTML
    #   run: |
    #     ./s/Terraform/Azure.Resources/Tools/ReportUnit.exe -OutputFile ./s/Terraform/Azure.Resources/Test_Report.xml ./s/Terraform/Azure.Resources/HTML_Reports/
    #   shell: bash

    - name: Upload Artifacts
      working-directory: ./s/Terraform/Azure.Resources
      uses: action/upload-artifact@v1
      with:
        name: HTML_Report
        path: Test_Report.xml
