name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Pester Tests
      run: |
        Invoke-Pester `
          -Script @{
            Path = "${{ inputs.working_directory }}/Azure.Resources/Tests/Verify-resource-group.Tests.ps1"
            Parameters = @{
            }
          }
      shell: pwsh