name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
runs:
  using: "composite"
  steps:
    - name: Run Pester Tests
      run: |
        Wrire-Output "Test"
        Wrire-Output "${{ github.workspace }}/Azure.Resources/Tests/Verify-resource-group.Tests.ps1"
        Invoke-Pester `
          -Script @{
            Path = "${{ github.workspace }}/Azure.Resources/Tests/Verify-resource-group.Tests.ps1"
            Parameters = @{
            }
          }
      shell: pwsh