name: 'Pester Tests'
description: This task to verify Azure resources using PowerShell Pester
inputs:
  working_directory:
    description: 'Path to the working directory'
    required: true
  client_id:
    description: 'test'
    required: true
  subscription_id:
    description: 'test'
    required: true
  tenant_id:
    description: 'test'
    required: true
  gh_secrets:
    description: 'test'
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure account list
      run: |
        az account list
        az group list
      shell: bash

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: "6dc14acc-6811-4599-b681-a06081e050dd"
        tenant-id: "3e4bd703-341f-4304-901c-63d23574b331"
        subscription-id: "4b09b3ee-592e-48fd-a985-cb26811b0967"
        enable-AzPSSession: true
        
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      continue-on-error: true
      with:
        inlineScript: |
          Invoke-Pester -Path "./s/Terraform/Azure.Resources/Test" -OutputFile "./s/Terraform/Azure.Resources/HTML_Reports/Test_Report.xml" -OutputFormat NUnitXML
        azPSVersion: "latest"
        
    - name: Convert XML to HTML
      continue-on-error: true
      run: |
        ls -al
        ./s/Terraform/Azure.Resources/Tools/ReportUnit.exe ./s/Terraform/Azure.Resources/HTML_Reports ./s/Terraform/Azure.Resources/HTML_Reports/
        cd ./s/Terraform/Azure.Resources/HTML_Reports/
        ls -al
        ls -al
      shell: bash

    # - name: test module
    #   id: test_module
    #   uses: zyborg/pester-tests-report@v1
    #   with:
    #     include_paths: ./s/Terraform/Azure.Resources/Test
    #     report_name: module_tests
    #     report_title: My Module Tests
    #     github_token: ${{ inputs.gh_secrets }}

    # - name: dump test results
    #   shell: pwsh
    #   run: |
    #     Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
    #     Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
    #     Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'

    # - name: Upload Artifacts
    #   uses: action/upload-artifact@v3
    #   with:
    #     name: HTML_Report
    #     path: ./s/Terraform/Azure.Resources/HTML_Reports

# Invoke-Pester -Path "Azure.Resources/Test" -OutputFile "Azure.Resources/Test/Test_Report.xml" -OutputFormat NUnitXML

# Azure.Resources/Tools/ReportUnit.exe Azure.Resources/Test/Test_Report.xml Azure.Resources/HTML_Reports/