name: Deploy Azure Resource
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Terraform Plan'
        uses: ./.github/actions/terraform
        with:
          working_directory: ${{ github.workspace}}
          tf_directory: ${{ github.workspace}}/Azure.Resources/TF_GitHub
          tf_plan: true
          tf_apply: false


        
