name: Deploy Azure Resource
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Azure Login'
      
        uses: azure/login@v1
        with:
          # client-id: '9743cd82-aa09-4cef-94e9-d50bdf246d3b'
          # tenant-id: 'bc540cd6-65a2-493d-8ec5-ee06f9bbb60e'
          # subscription-id: '4b09b3ee-592e-48fd-a985-cb26811b0967'
          # creds: '3G88Q~e971mytj2~deQX_4.breNhd50W30lOndd7'
          # creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: 'Terraform Plan'
        uses: ./.github/actions/terraform
        with:
          working_directory: ${{ github.workspace}}
          tf_directory: ${{ github.workspace}}/Azure.Resources/TF_GitHub
          tf_plan: true
          tf_apply: false

      - name: 'Terraform Apply'
        uses: ./.github/actions/terraform
        with:
          working_directory: ${{ github.workspace }}
          tf_directory: ${{ github.workspace}}/Azure.Resources/TF_GitHub
          tf_plan: false
          tf_apply: true
   
  pester_tests:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:   
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: s/Terraform
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: 'Pester Tests'
        uses: ./s/Terraform/.github/actions/pester_tests
        with:
          working_directory: s/Terraform
        
        
        
