name: GitHub_Runner_Workflow

on: workflow_dispatch
permissions:
    contents: read
    pages: write
    id-token: write
    actions: write
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'Azure Login'      
              uses: azure/login@v1
              with:
                client-id: "8b5273fc-e753-41cb-a3e0-a2ec8ece9a79"
                tenant-id: "bc540cd6-65a2-493d-8ec5-ee06f9bbb60e"
                subscription-id: "4b09b3ee-592e-48fd-a985-cb26811b0967"
                enable-AzPSSession: true
            - name: 'Build GitHub Runner container image'
              uses: azure/docker-login@v1
              with:
                login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                docker build --build-arg RUNNER_VERSION=${{ env.RUNNER_VERSION }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/pwd9000-github-runner-lin:${{ env.RUNNER_VERSION }} .
    