# This is a basic workflow to help you get started with Actions

name: First Workflow
on: workflow_dispatch
jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello World!"
          echo "Hello World 2!"
      - name: print good bye
        run: echo "Good bye!"
